apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # Should I use a beta tag here
  name: cheetahs.alpha.com
spec:
  scope: Namespaced
  group: alpha.zipcar.com
  versions:
  - name: v1
    served: true
    storage: true
  names:
    plural: cheetahs
    singular: cheetah
    kind: Cheetah
    shortNames:
    - cheet
